### ISSUE TITLE
Adding CORS 

### ISSUE THREAD

**Issue by Fl4zher** [iaincollins/nextjs-starter#103]
Hi

I want to make an API call to another server, but it gets denied because of CORS. I've tried to enable cors with the npm package. But i don't see it on the request header. Am i doing something wrong? 

I've simply added this to the "index.js" <- express server
```
expressApp.use(cors());
```

**Comment by Fl4zher** [comment]
Nevermind, found out that it's because the API runs at HTTPS, and my local website is running on HTTP. Fixed it with a plugin on firefox.

**Comment by ariadi** [comment]
@Fl4zher : Just want to know. How do call API with jwt or user/password authentication use this starter-kit?
