### ISSUE TITLE
Possible null user?

### ISSUE THREAD

**Issue by katopz** [iaincollins/nextjs-starter#13]
By any chance, Is that possible user [here](https://github.com/iaincollins/nextjs-starter/blob/master/routes/passport-strategies.js#L130) can be null?

Thanks

**Comment by iaincollins** [comment]
Your right, it's unlikely it can be!

It should only happen if someone has logged in then their account has been deleted while their session is still logged in, then they have tried to link their account with an oAuth provider like Facebook, Twitter or Google+ (which isn't currently possible in this example, as the sign in buttons are not displayed once you are signed in, but it should be catered for).
