### ISSUE TITLE
Update Session component to add Redux Store and use connect()

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/nextjs-starter#2]
The Session component works perfectly fine, well am considering refactoring it in a more typical React/Redux pragma by using a Store as a practical usage example.

The Clock demo that's included (from the official wiki) uses a Store and connect() but it's not the easiest (or most re-useable) example to follow.

I can't see a huge practical benefit from the point of view of application behaviour and I'm not sure if this would make the logic easier to follow, more bloated, or even make the logic harder to follow, but it's an established pragma so seems worth considering.

(I already use a Store with connect() for session handling in another project, I'm just not quite sure the pragma is justified over using more easily readable vanilla JS for the same thing).

I am also tempted to set up an event handler to listen for events on the session store and/or fire server events showing how that if you perform an action (like sign in or out) in one tab/window that it can automatically update other tabs/windows.

Comments/suggestions around this welcome.

**Comment by iaincollins** [comment]
As of version 2.3.4 all pages now automatically inherit the current session info by extending a Page component which exposes it in this.props.session - this removes the need for boilerplate on every page.

In React, props should be immutable, so this approach need to be refactored in future. I have a couple of ideas but would welcome suggestions as to the best way to handle that.

Once I have a pragma in place for that, it would be great to use it leverage Broadcast Channel API (currently only available in Chrome and Firefox) to be able to auto update the session state in any other open browser windows or tabs any time the session state changes.

**Comment by sedubois** [comment]
> am considering refactoring it in a more typical React/Redux pragma by using a Store

I'm interested in what's possible to do about this, especially in combination with Apollo.

> this approach need to be refactored in future

I'd suggest trying a higher-order component (e.g called `withSession()`) similar to the `withData()` present in the Apollo example https://github.com/zeit/next.js/blob/master/examples/with-apollo/lib/withData.js.

Right now I'm still very much struggling to assemble authentication in my Next.js + Auth0 + Graphcool + Apollo webapp https://github.com/relatenow/relate and all help is appreciated 🙂 I'm having struggle with:
- swapping out your custom auth provider with the Auth0 provider I want to use (or at least anything that provides Facebook + login/password)
- swapping out your custom user storage with my Graphcool backend

It would be great to be able to reduce the API surface and would be even more fantastic if this could then be made into an NPM lib 😉

**Comment by iaincollins** [comment]
I'm really happy to provide an an example with oAuth (Google, Facebook, GitHub, Twitter, etc) but I'm worried about how the level of complexity required would put people of who just wanted something simple. 

I actually have a working example in a local version of the repo, but I haven't bothered to cater for the edge cases in it, which I haven't published as I'm worried it will mislead folks into implementing it badly (in particular, insecurely) on their own.

A problem with oAuth integration is it's all very application specific. There are lots of edge cases with oAuth, especially if you also allow email based logins (as most sites do) and if you have multiple providers (as is also very common).

It ties in very closely to the database being used to store the tokens, and there are custom pages for linking/unlink oAuth providers with accounts and handling errors when logging in with say a Facebook account that is associated with an email address that already belongs to an existing user (because they signed up via email but didn't link the accounts originally). It's edge case stuff but if you ignore it then users have a bad time (and can potentially have their accounts hijacked).

This all means you will need logic specific to your database (to add users, fetch and update tokens) and custom  pages with routes for different scenarios. As people will always want to be able to customise those pages; it's hard to make them generic.

Additionally, the oAuth spec is a bit vague. It's better since 2.0 but error handling between providers and the contents of user profiles still vary a lot. For example, some sites like Twitter don't return email accounts which necessitates a degree of provider specific logic if you also allow email based logins.

There is a great node project called the [hackathon-starter project](https://github.com/sahat/hackathon-starter) that I can recommend for oAuth examples.

I would love for it all to be a simple module, and I think some of it could be abstracted, but people would always need to create their own pages and be able to define their own logic for database handling, so I think it's one of those things that is doomed to be site specific (at least until the oAuth spec is tightened) with examples in starter projects to help folk with their own implementations.

I haven't given up on pushing the oAuth examples I've already done though (they are reasonably well commented at least). If I do, I'll create a simple /profile page so people can easily view their current profile data to help explain how it works.

**Comment by sedubois** [comment]
Okay there are still some issues to fix (like page refresh when logging in/out and page transitions are much slower now when deployed), but I got something mostly working! https://github.com/relatenow/relate

(I'll deploy when those things are fixed)

Thanks for the pointers you shared 🙂

**Comment by iaincollins** [comment]
@sedubois Oh cool that's that working :)

I got oAuth (with Facebook, Google+ and Twitter examples included) now and resolved previous outstanding issues so this is the only thing remaining. It also uses the ORM layer so is easy to switch databases (doesn't cover everything but there are drivers for popular choices).

I might look at seeing if auth (with Passport) can be made a lib for Next.js in a couple of weeks. It's certainly possible but even despite the effort to minimise the work, would require some code-as-configuration which isn't ideal (especially for checking for, creating and associating/dissociating accounts with providers, and for configuring each provider which is quite a bit).

The latter could be minimised a lot by shipping with build in support for a full range of properties and options from each provider, but I suspect I don't have the time for that.

I wish it was easier for folks to setup (even though Passport is super helpful). Even configuring oAuth on developer portals and debugging it is a pain as the oAuth 2 standard, while a lot better than oAuth 1, is still ambiguous about a lot of stuff, especially provider configuration and error handling.

I will take a look at your examples - thanks for that BTW. I don't really have my head around the concepts in it yet to be honest but looks very relevant.

**Comment by iaincollins** [comment]
I'm not going to refactor it into a Store after all, but I am going to simply the Session class (probably with unfetch to avoid the additional boiler plate using XMLHttpRequest adds).

I'm going to add a simple cross-page Counter example as an example of a Store that works both client and server side.
