### ISSUE TITLE
Error handling for client-side routing

### ISSUE THREAD

**Issue by narin** [iaincollins/nextjs-starter#20]
Just discovered your project today and it is awesome.  Thank you for putting it together!

I noticed that the error page does not show up if the user is routed to an invalid page client-side.  Seems to work if I remove the custom error page.

**Comment by iaincollins** [comment]
@narin Hey, I see what you mean.

I did some digging, tried some stuff out and and I can't see how to handle that actually; I think Next.js does not support redirecting to the 404 page when following a link to a non-existant page on client side, at least not with a custom router.

I agree it makes sense to fall through to the 404 page but I just can't see how to do that. You might want to raise this one as an issue with the Zeit folks over on the Next.js repo if you would like to see them add support for it.

* Note that if link is to a page, like "/articles/1234" where "1234" is an article ID and "pages/articles.js" handles all routes to "/articles/*" you still have the option of generating a 404 from there, but I appreciate that doesn't help for links like "/wrong-url/1234".

**Comment by iaincollins** [comment]
I'm going to close this one for now, but think it's worth asking about and - if there still isn't an option for it - raising it as an issue in the next-js repo. There have been some changes to error handling since I created this project but I'm not sure if there is a way to resolve this issue or not.
