### ISSUE TITLE
npm run dev issue

### ISSUE THREAD

**Issue by koutsenko** [iaincollins/nextjs-starter#21]
MacOS, i cloned the repo and did **npm i**. Then I tried to run it:
```

bash-3.2$ npm run dev

> nextjs-starter@2.9.0 dev /Volumes/EXFAT-1Tb/Work/nextjs-study-starter
> NODE_ENV=development PORT=3000 node index.js

/Volumes/EXFAT-1Tb/Work/nextjs-study-starter/routes/auth.js:22
exports.configure = ({
                     ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)

```

Node.js version is 4.7.3.
Why it dont want to run?

**Comment by iaincollins** [comment]
Hi there @koutsenko,

The current version of Node.js is version 7 and any release of version 7 should work fine (that's also what is declared in package.json, though you might be fine with version 6 too).

The project uses syntax not supported in version 4 in the server side only code, as it improves readability and reduces the amount of code (in particular as in the auth.js route handler, where there are options defined with default values - which is not supported before version 6 as they are ES6/ES2015 features).

**Comment by koutsenko** [comment]
Yeah, it works in node@6 now. Thanks.

**Comment by jesmarquez** [comment]
Hi!

Failed at the nextjs-starter@2.13.0 dev script 'NODE_ENV=development PORT=3000

Node 6.9.1
Windows 10

Environment variable has NODE_ENV=development and PORT=3000
Any help!
