### ISSUE TITLE
PropTypes Error on live demo and local testing

### ISSUE THREAD

**Issue by diegochavez** [iaincollins/nextjs-starter#24]
Hi, I've noticed this on my console.

`app.js:3 Uncaught TypeError: Cannot read property 'PropTypes' of undefined
    at Object.o.23.113 (app.js:3)
    at a (app.js:3)
    at app.js:3
    at Object.o.38.113 (app.js:3)
    at a (app.js:3)
    at app.js:3
    at Object.o.31.10 (app.js:3)
    at a (app.js:3)
    at app.js:3
    at Object.o.47.1 (app.js:3)`

**Comment by iaincollins** [comment]
Thanks for raising this, I had seen this problem but I had seen some unexpected errors in dev mode recently that I think might have been triggered by an upgrading from an earlier Next.js 2.0b release.

WiIl investigate.

If you happen to know the browser you were using and what page you were on (if relevant) that would be helpful.

**Comment by diegochavez** [comment]
No problem, yeah could be related to the latest release next, this problem is visible in production mode, running on dev mode doesn't show any error. 

> MacBook Pro
Chrome 57.0.2987.133 (64-bit)

![babel-language settings entry](https://content.screencast.com/users/diegochavez/folders/Jing/media/cbe193e0-fe0b-43d8-80c1-e5034ac14e16/00000393.png)

Firefox
Looks like is the same problem but more descriptive message.

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

I'll look forward on this too :) 

Thanks mate,

**Comment by iaincollins** [comment]
Not found time to look at this yet but will do soon. Thanks again for the detailed report!

**Comment by iaincollins** [comment]
Was able to replicate and resolve now with an upgrade to the latest version of Next.js.

Version 2.12 has been upgraded to use Next.js 2.4 which seems to resolve the issue, it should be live in a few minutes.

**Comment by diegochavez** [comment]
Awesome thanks @iaincollins
