### ISSUE TITLE
Production Mode - Building

### ISSUE THREAD

**Issue by bryan** [iaincollins/nextjs-starter#3]
The instructions didn't work for me, I had to run `npm run build` instead of `npm build` in order to get it to work.

**Comment by iaincollins** [comment]
Hi @bryan thanks for the issue.

I think this happens on earlier npm versions.

Could you report back with your npm version to confirm so I can update the README accordingly?

For reference I'm running:

$ node -v
v6.2.1
$ npm -v
3.9.3

**Comment by bryan** [comment]
Not a problem. I'm also running Ubuntu 14.04. 

$ node -v
v6.9.2
$ npm -v
3.10.9

**Comment by iaincollins** [comment]
Huh, that's weird; I'd thought it it was an npm 2.x thing but you are more up to date than me.

Thanks, will change the docs as 'npm run build' should work for everyone regardless.
