### ISSUE TITLE
Fetching data on server & client side

### ISSUE THREAD

**Issue by adrianha** [iaincollins/nextjs-starter#33]
Hi @iaincollins ,
Thank you for this starter.
I wanna ask about data fetching on async example.
i saw you are fetching the data in https://github.com/iaincollins/nextjs-starter/blob/master/pages/async.js#L21 and https://github.com/iaincollins/nextjs-starter/blob/master/pages/async.js#L40.
So it will fetch the data twice when user opened that page? L21 will be called on server side and L40 will be called on client side.

**Comment by iaincollins** [comment]
Good question!

So the two scenarios:

1. If you are coming from another page on the site then it will only fetch on the client.

2. If it's the very first page you visit on the site then as it is currently it will call the endpoint both on server, then it will fetch the latest version again on the client.

If undesirable, this can be avoided by just checking the state in componentDidMount(), the state should be inherited from the server side render:

``` javascript
async componentDidMount() {
  if (this.state.posts.length === 0) {
    this.setState({
      posts: await AsyncData.getData()
    })
  }
}
```

One caveat is your app is behind a CDN with server rendered responses being cached (and so might not be as fresh) you might just want to have the client always display the latest data from the API.

However, it's probably worth updating the example with something like the above, with a comment to explain the rationale.

**Comment by adrianha** [comment]
Yes, thats the scenario i faced now.
I think your solution will be ideal if not using redux.
But currently i'm using redux to manage data flow on my app. So here's my current solution:
```
static async getInitialProps({ store, isServer }) {
    if (!process.browser) {
      await store.dispatch(requestData());
    } else {
      store.dispatch(requestData());
    }
  }
```
I will be waiting for the promise to be resolved on the first time load. While navigating on client side, i wont wait the promise to be done. What do you think about this approach?
Thanks!

**Comment by iaincollins** [comment]
Sorry for not responding sooner.

Hmm, I think I'd need to know more about the store and specific use case to give any useful input.

I've actually ended up using mobx in my production apps because I didn't like redux so much, and it's worked really well for me and I've found it much simpler to implement - but I'm not really qualified to comment on redux patterns.

I'm currently using a mobx store (and `componentDidMount()` to set state) in a couple of projects. I wrote a small store with a counter just as a test while I was evaluating it. It's quite a nice simple example, maybe I should add it for reference?

**Comment by adrianha** [comment]
Yeah sure @iaincollins , it would be better if there are more examples. Thanks

**Comment by jesmarquez** [comment]
Hi,

I have an error when I do fetch:

    const response = await fetch('/savepassword', {
        method: 'POST',
        body: formData
    });

**Comment by iaincollins** [comment]
I've improved the AJAX example and documentation, based on the thread above. I'm going to close this off but let me know if you think it could be improved further.

@jesmarquez You might want to take a look at `auth/profile.js` and use the `unfetch` module when creating requests to POST data. Unlike isoorphic-fetch, unfetch is able to send cookies with requests so works with CSRF. You can also use XMLRPC (but unfetch is nicer syntax).

**Comment by Flo-Slv** [comment]
Hi @iaincollins  !
I have still the same issue like jesmarquez when i try to POST formData. CSRF token is missing.

I try with isomorphic-fetch, unfetch and XMLHttpRequest... :/

I have no issue when i send an 'application/x-www-form-urlencoded' request but this is not what i want. I would like to send a formdata.

Thanks from France

**Comment by iaincollins** [comment]
Hi @Flo-Slv,

This example project only has an example for `application/x-www-form-urlencoded` (used for typical forms) but doesn't have anything `multipart/form-data` forms (as used by the FormData API).

NextAuth in this project adds CSRF protection to all POST routes by default, so all POST requests must include CSRF Tokens, which is causing you to run into a CSRF Token error.

You can try adding a CSRF Token to your call…

e.g.
    `formData.set('_csrf',  this.state.session.csrfToken)`

…or…
    `formData.set('_csrf',  await NextAuth.csrfToken()`

…but I don't know for sure if the current implementation used for CSRF protection will work with `multipart/form-data` forms, but I'm happy to reopen this issue until that has at least been reviewed.

For now, I recommend creating a new blank Next.js project that doesn't use NextAuth and getting that working with your FormData call, which should be much simpler.

I will leave this open until I have answer to if `multipart/form-data` works with NextAuth at some point. Something that might be added to NextAuth soon is the ability to disable CSRF Token protection on certain routes which might be relevant.

**Comment by curran** [comment]
@Flo-Slv FWIW, I managed to get the CSRF check to work using `fetch`, like this:

```js
      const options = {
        credentials: 'include',
        method: 'POST',
        headers: {
          'x-csrf-token': csrfToken,      
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ html })
      };
      const response = await (await fetch(url, options)).json();
```

**Comment by kelleg1** [comment]
@curran's method of putting 'x-csrf-token' in the headers works to send a CSRF token to the server using fetch, but propagating the CSRF token from the page's props.session.csrfToken through to the fetch call leads to a 'CSRF token mismatch' error. I'm not sure why there is a mismatch.

**Comment by chakya** [comment]
@iaincollins Hi I tried creating a POST endpoint on ```api/post.js```

I'm able to pass the CSRF token validation however my post.js didn't get executed. GET endpoint works so I don't know what's the problem with my POST endpoint.

Any examples on creating API endpoint?
