### ISSUE TITLE
Unsupported platform for fsevents - Installation

### ISSUE THREAD

**Issue by jesmarquez** [iaincollins/nextjs-starter#36]
Hi!

I install and it show this error message!

Unsupported platform for fsevents@1.1.1: wanted {os:darwin, arch:any} {current: os linux, arch:x64
Any help!

**Comment by iaincollins** [comment]
Hmm this seems to be an issue specific to running on Windows.

It's it's good to know about but I'm not sure what to suggest. Quite a few npm modules don't run well natively on Windows so it's often easier to just to run node apps inside a virtual machine.

You can using this to install and see how you get on - this should skip optional dependancies and might help:

`npm install --no-optional`

Interested to hear how you get on!

**Comment by jesmarquez** [comment]
With Linux too!

I add this lines package.json:
  "optionalDependencies": {
    "fsevents": "*"
  }

And run: 
npm install --no-optional

Work it!

Thanks!

**Comment by iaincollins** [comment]
Thank you! I'll add that to package JSON and to the Readme!

**Comment by iaincollins** [comment]
Thanks again!

Have incorporated this into the README and package.json so closing this issue off now.
