### ISSUE TITLE
nextjs development env session created for each request (on-demand-entries type request)

### ISSUE THREAD

**Issue by mihaiserban** [iaincollins/nextjs-starter#40]
Hi,

I'm running your nextjs starter example in development mode, and i assume many requests are triggered due to dev mode and hot reloading. Requests such as http://localhost:3000/_next/on-demand-entries-ping?page=/

For each request such as this a new session is created, and /tmp/sessions easily gets filled with alot of session files. 
Have you encountered this issue? Is there any way to avoid creating new sessions for each nextjs ping request?

**Comment by iaincollins** [comment]
Sorry for the delay in response, I'm going back through old issues I;ve missed.

Ugh yes that's annoying (and /tmp/ being filled is bad) and bugs me too. The next update uses an in memory store for sessions to avoid this, but that doesn't address the issue you raise of it creating new sessions for ping requests.

I guess a rule for express to ignore creating sessions on routes under /_next would be fine, though I'm not sure how to do that off hand. Will leave open until we have a solution.

**Comment by iaincollins** [comment]
This is now resolved - the project no longer uses the file system for temporary sessions and instead uses an in-memory database if no database is configured.

This is a lot easier as it it's deleted when the server is stopped and doesn't fill up the disk (which was a confusing thing to run into and it wasn't handled well by the middleware).
