### ISSUE TITLE
Update username, email, profile image

### ISSUE THREAD

**Issue by kamish24six** [iaincollins/nextjs-starter#42]
Thanks!

**Comment by iaincollins** [comment]
Have an update in the bootstrap branch that will be out soon (and I'll push into master) that has editable profile pages.

It doesn't store profile images yet, but that's a good idea for a feature to include.

**Comment by iaincollins** [comment]
The latest example now supports updating the name and email address via a profile page at http://nextjs-starter.now.sh/auth/profile 

I haven't added importing profile images, but that's something I'll look at adding in a future update.

For now folks interested in this may wish to take a look at Gravatar.
