### ISSUE TITLE
Why can't header and Layout be functional components?

### ISSUE THREAD

**Issue by prabu-ramaraj** [iaincollins/nextjs-starter#43]
Wondering, why header and layout components are extended from React.Component?  These components are not using state or lifecycle hooks.  Why can't they be functional components?  Correct me if I am wrong.

**Comment by iaincollins** [comment]
Thanks for this comment!

You're right, I think a lot of the components could be refactored to be functional components.

I'll do this in a future update to the bootstrap branch, which I'm currently working on.

Example for reference for folks wondering what this is about: 
https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

**Comment by iaincollins** [comment]
Going back on what I've said above, as things have moved on I've decided against this - the layout and header components have been refactored and I don't think it makes as much sense now (it's still possible, but then would need to explain in comments what's going on and wy).

Overall things are simpler, but there is more logic in the layout - a tradeoff for readability in an example project where the primary goal is ease of comprehension - and it's seems reasonable that people playing around with the project might want to expand it in their own projects, so leaving as a React.Component makes the most sense I think.

It's a good point though and might be good to apply elsewhere. It's certainly something that would be good to include as an example in the 'performance' documentation section, even if it's if only by way of explaining why some components are sometimes written this way now.
