### ISSUE TITLE
Update to Next.js 4.x and React 16

### ISSUE THREAD

**Issue by iaincollins** [iaincollins/nextjs-starter#44]
Currently this project uses reactstrap, which has React 15 dependancies, so the project is still on Next.js 3.x (which uses React 15).

Either I'd like to refactor the project not to use reactstrap and just use CSS and className properties on HTML elements (the modal for the sign in pop up and the profile would be the most work, but every template would probably need to be touched).

Alternatively, it would be great if reactstrap was updated to support React 16, but I have no idea how much work is involved in doing that.

Pull requests to address either of these (i.e. either to reactstrap or to this project) would be amazing.

**Comment by sethbergman** [comment]
I'm not sure about the support for reactstrap, but I do know that you'll need to upgrade to React 15.6.x before upgrading to 16.x. There's a good article covering some of the tools needed here:
https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6

**Comment by iaincollins** [comment]
Thanks @sethbergman! The project has been updated to React 16 - largely as already using React classes I didn't need to make any changes. Reactstrap now has an alpha that supports React 16, so was able to upgrade to to Next.js 4 too.
