### ISSUE TITLE
It's possible to replace the mongoClient to mongoose? 

### ISSUE THREAD

**Issue by kamish24six** [iaincollins/nextjs-starter#50]
I have trouble with connect between collection in mongoclient and i want to use the mongoose populate function. can i replace the mongoclisnt with mongoose?

**Comment by iaincollins** [comment]
The short answer is yes, if you were to edit `passport-strategies.js` and `auth.js`, but it's not as obvious or easy as it could be.

I intend to make it easier by refactoring `passport-strategies.js` and `auth.js` to take `addUser` and `updateUser` methods as arguments and then provide examples of how it could be used with any database.

I'll leave this issue open until that's resolved (or a new issue to resolve it is created).

**Comment by iaincollins** [comment]
Version 4.5.0 of this project just went live and now includes totally renewed authentication, with database interaction fully split off into a separate module.

It's similar code for authentication under the code, but much simpler to customise as all the authentication code that it was possible to split off now lives in the NextAuth module.

Configuration is split into three files:

* next-auth.config.js - Basic configuration options (server name, etc)
* next-auth.functions.js - CRUD methods for user accounts and sending email (etc)
* next-auth.providers.js - oAuth Provider configuration (examples for Facebook, Google, Twitter)

All database interaction is now defined in 'next-auth.config.js', so if you wanted to add your own methods to ineract with Mongoose you can now define them there.

Unfortunately I don't have the time right now to provide a Mongoose specific example, and I appreciate it's not easily possible to upgrade old projects to use the new method (it's probably going to be easier to clone this project again) but hopefully it will be easier for new users.

(If you do come up with a Mongoose configuration and would like to share it I'd love to include it!)

**Comment by kelleg1** [comment]
This is the next thing I am working on. I need to connect to multiple databases using Mongoose, but Mongoose only allows the 'use db' command (as of a recent patch), or instantiation of multiple Mongoose instances via the constructor. I am probably going to go with multiple Mongoose instances.

I'm having trouble getting Mongoose to connect in the route when using multiple instances, as well as trouble getting it to retrieve a document when using a single instance.

Here is some code I was testing with when using a single Mongoose instance (I know I should connect outside of the route, but I decided to put it inside during testing). The route fires, but hangs on MyModel.findOne(). Not sure what's wrong.

**routes/myroute.js:**
```
const mongoose = require('mongoose');
const path = require('path');

mongoose.Promise = require('bluebird');

module.exports = (expressApp) => {
	if (expressApp === null)
		throw new Error('expressApp option must be an express server instance');

	expressApp.get('/test', async (req, res) => {
		const Mongoose = new mongoose.Mongoose(); // Create a new Mongoose instance
		const connection = await Mongoose.connect('mongodb://localhost:27017', function(err) {
			if (err) {
				console.err(err);
			} else {
				console.log('Connected');
			}
		});
		const MyModel = await require('../mongoose/models/MyModel');

		const myModel = await MyModel.findOne({});
		console.log('Fetched');
		console.log(myModel);

		return res.json({
			name: myModel.name,
		});
	});
}
```

**mongoose/models/MyModel:**

`const mongoose = require('mongoose');
const path = require('path');
const Schema = mongoose.Schema;

const modelName = 'MyModel';
const collectionName = 'docs';

const schema = new Schema({
	name: String,
});

module.exports = mongoose.model(modelName, schema, collectionName);
`

**Comment by kelleg1** [comment]
@iaincollins Nevermind, the problem was with my connection code! I needed to call mongoose.connect() instead of (new mongoose.Mongoose()).connect(). That was a hold over from the application I copied it from that was using multiple instances.

**Comment by kelleg1** [comment]
Still having trouble getting my code to use multiple connections, not sure why. I'm kind of wondering if the routes are ran on both the server and the client?

**Comment by kelleg1** [comment]
Nevermind again. The issue appears to have been with the version of Mongoose I was using. In the newer version, I had to use Mongoose.createConnection() when using an instance of Mongoose as opposed to Mongoose.connect() which works when using Mongoose as a singleton.
