### ISSUE TITLE
Bug: "Failed to serialize user into session" in facebook register 

### ISSUE THREAD

**Issue by kamish24six** [iaincollins/nextjs-starter#54]
This only happens for the first time. After the user is saved, you can reconnect and it works fine

**Comment by kamish24six** [comment]
I solved the problem. For some reason, in the passport.serializeUser function, when the user is register, the user object came as a ops object ( i'm using Mlab).

I add the following code to the function, and now it's all fine. 

` passport.serializeUser((user, next) => {
    let id = (user.ops) ? user.ops[0]._id : user[userDbKey];
    next(null, id)
  })`

**Comment by iaincollins** [comment]
Interesting! Thanks for the report and the suggested fix, and that you are using mLab, which is helpful for trying to replicate it.

I don't understand why that's happening, but I'll try to replicate with a blank MongoDB in mLab and apply the fix if I see the same thing. If not will come back and report what I found.

**Comment by iaincollins** [comment]
I don't see this, but have some some refactoring since.

If anyone sees this please do re-open the issue.

**Comment by iaincollins** [comment]
Thanks again for raising this. I think I did find an issue in passport-js which might have triggered this on first login when configured with MongoDB.

**Comment by iaincollins** [comment]
(I now understand what you were saying about the ops object, I have no idea why I didn't see that happening before!)
