### ISSUE TITLE
[QA] - How to add "awesome font" using self-hosted

### ISSUE THREAD

**Issue by minhnguyenwp** [iaincollins/nextjs-starter#56]
Any way to import Fonts and image in scss. If i put them on a static folder. Pls help me this problem

**Comment by kamish24six** [comment]
Try using static folder. For example: 

app.use(express.static('public'))

**Comment by iaincollins** [comment]
Hi @minhnguyenwp, sorry I didn't see this earlier.

Next.js actually serves content from a static folder by default, so if you put them in a folder called "/static/" you can access them from there (e.g. /static/fonts/myfont.tff).

I'll add some example content in there so the project has some for folks to reference.

**Comment by minhnguyenwp** [comment]
@iaincollins Thank you. i found out it. but i think if NEXTJS has a kit starter likes "React Kit Starter", it will be more awesome. i have to config many functions with Webpack.

**Comment by iaincollins** [comment]
Hi
