### ISSUE TITLE
Request for MySQL compatible example

### ISSUE THREAD

**Issue by naysumyat** [iaincollins/nextjs-starter#65]
would be great if this has mysql version too.

**Comment by iaincollins** [comment]
It would be super useful to have that, and include it in **next-auth** too.

I don't have the time to do that right now, but if anyone would like to contribute an example of an **next-auth.functions.js** for MySQL - and an example of the table structure it needs - I'd love to include it.

**Comment by iaincollins** [comment]
For anyone interested in this, please see this issue with next-auth:
https://github.com/iaincollins/next-auth/issues/5

There is documentation in the next-auth wiki for what the functions should do:
https://github.com/iaincollins/next-auth/wiki/Functions
