### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by kelleg1** [iaincollins/nextjs-starter#66]
Hi Iain,

Very much appreciate the work you are doing on this project and the refactoring to use the next-auth module you developed. It looks like a major step in a great direction. I am checking out your code now and it looks like I will be able to modify it a lot easier to do what I need.

However, I ran into a minor issue, which is that when I try to generate a sign up link by entering my email address, I get this error. Prior to the refactoring to use next-auth, the app would send me an email without configuring any email server settings in .env.default. I don't have a spare email server handy to use in development. Is it possible to get this functionality back?

```
Error sending email to XXX@gmail.com { Error: connect ECONNREFUSED 127.0.0.1:25
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25,
  command: 'CONN' }
```

**Comment by iaincollins** [comment]
Hi @kelleg1,

Good point - we should add that behaviour back in out of the box in this project and in the next-auth default example.

For now, if you replace the `sendSignInEmail` function in `next-auth.functions.js` with something like this it should restore the previous functionality.

Note: The only issue with using `nodemailer-direct-transport` is that emails often get caught in spam traps and sometimes users never get to see them, but if it works for you it's totally fine.

````javascript
const nodemailer = require('nodemailer')
const nodemailerDirectTransport = require('nodemailer-direct-transport')

…

sendSignInEmail: ({
  email = null,
  url = null
  } = {}) => {
  nodemailer
  .createTransport(nodemailerDirectTransport()
  .sendMail({
    to: email,
    from: process.env.EMAIL_FROM,
    subject: 'Sign in link',
    text: `Use the link below to sign in:\n\n${url}\n\n`,
    html: `<p>Use the link below to sign in:</p><p>${url}</p>`
  }, (err) => {
    if (err) {
      console.error('Error sending email to ' + email, err)
    }
  })
  if (process.env.NODE_ENV === 'development')  {
    console.log('Generated sign in link ' + url + ' for ' + email)
  }   
}
````

**Comment by kelleg1** [comment]
@iaincollins
Great! I didn't realize I needed to use nodemailer-direct-transport. I'll modify my code so it uses that when NODE_ENV == development.
I understand about the spam filters.
Thanks Iain!

**Comment by iaincollins** [comment]
As a follow up, I have now added this back as fallback behaviour to nextjs-starter and added it to the next-auth example config.
