### ISSUE TITLE
SyntaxError: Unexpected Identifier

### ISSUE THREAD

**Issue by bmeteor** [iaincollins/nextjs-starter#71]
All I did was clone the repo and ran npm install && npm run dev. Is there something I have to setup further to get this running locally?

**Comment by iaincollins** [comment]
That should be all you need to do!

$ node -v
v7.10.1
$ git clone https://github.com/iaincollins/nextjs-starter.git
$ cd nextjs-starter/
$ npm install && npm run dev

I've just checked it out and installed and built now and it's gone okay here.

Could you confirm:

1) The version of node you are using.
2) The full error message.
3) The OS you a reusing (sometimes there are OS specific issues with dependancies).

If there are problems with an older version of node it's probably not going to be possible to resolve as I think there are dependancies that don't work with 6.x and older, but if it's with 8.0 happy to take a look!

**Comment by bmeteor** [comment]
yea it's me... i did it on my other mac and it worked I think it's my node version.

**Comment by bmeteor** [comment]
btw really grateful for the work you've done here it's really helped me a lot learning.

**Comment by iaincollins** [comment]
Oh good I'm glad it's working.

This is a good reminder that I probably need to bump it to Node.js 8 already ([as unlike v6, v7 isn't LTS](https://github.com/nodejs/Release)).

It's helped me to do this project too and was inspired by this [great node starter project](https://github.com/sahat/hackathon-starter) (which isn't React or Next.js specific, but does a lot more).
