### ISSUE TITLE
Setting a password for the user who logins with email

### ISSUE THREAD

**Issue by mohammedzamakhan** [iaincollins/nextjs-starter#74]
Can you add password field to the sign in form, so that the user can set the password for the email, and then when he comes to after signing out, he can just login with his email/password?

**Comment by iaincollins** [comment]
It's possible [and NextAuth has an an example of how to do it](https://github.com/iaincollins/next-auth/tree/master/example) but it's not recommended and is not provided as an example to discourage folks from doing it.

One-time, single use tokens are generally better approach, as it protects users either if your site is compromised, or if another site they were to use the same password on was compromised.

People often get storing passwords wrongly (old hashing functions, no per-user salt value or too small per-user salt value, etc) which is partly why it's discouraged in this example.
