### ISSUE TITLE
Starting in development mode on Windows

### ISSUE THREAD

**Issue by cmon2** [iaincollins/nextjs-starter#75]
Hey,

I can't get the app to run in Development mode.

Cleary "NODE_ENV=development PORT=3000 node index.js" won't work on windows so I switched it up with "SET NODE_ENV=development PORT=3000 && node index.js". Still the app will start in production mode on port 80.

Can you give me directions on what I could try further? Also maybe the readme could be updated for windows users.

**Comment by iaincollins** [comment]
Thanks for raising this. I agree, the instructions for Windows should be better.

I would actually expect what you have (`set NODE_ENV=development PORT=3000 && node index.js`) to work and not sure why it doesn't. Using `NODE_ENV=development PORT=3000 npm run dev` should also work, though is obviously more cumbersome.

I don't have a Windows system to hand right now to investigate further but am going to leave this open until there is a resolution.

**Comment by geordankeller** [comment]
Change the line to cross-env NODE_ENV=development PORT=3000 node index.js
and run "npm install cross-env --save-dev"
cross-env is needed on windows in order to set environment variables. cross-env is cross-platform.
