### ISSUE TITLE
Question about the session method

### ISSUE THREAD

**Issue by shmulikkaminker** [iaincollins/nextjs-starter#77]
When I browse to the address https://nextjs-starter.now.sh/auth/session, even when there is no active user I get a session. 

For example: {"maxAge":604800000,"revalidateAge":60000,"csrfToken":"iV9E1fdfdOfdfa2tHmffdayAiRRFT892lFgddfJFVa8d6XJGFg="}

Why does this session exist when the user is not logdin, and how can I check whether the user is logged in or not and whether his session is valid?

**Comment by iaincollins** [comment]
You don't need to login to create a session. This is very typical behaviour on most sites when not logged in (though actually may not be the default in future versions of NextAuth).

If you are logged in you should have a user object in your session (e.g. session.user = { name: "Joe", email: "joe@example.com }). Try logging in then taking a look at the session object for an example.

Note that the actual session ID is not exposed to the client via JavaScript / localStorage as protection against Cross Site Script Attacks, and is only stored in an HTTP Only cookie.
