### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by lagivan** [iaincollins/nextjs-starter#79]
Unfortunately, this starter is not compatible with IE11 - it fails both in DEV and PROD modes. It's acceptable for DEV mode, as webpack-hot-middleware is not compatible. However, in PROD mode I'd expect IE11 to work well.

Steps to reproduce:
1. Run with `npm run start` and open in IE11 or simply open https://nextjs-starter.now.sh/ in IE11
2. First, it shows the website content, then returns "HTTP Error" page with the following error in the console:

```
Syntax error
SyntaxError: Syntax error
   at Anonymous function (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:103573)
   at t (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:102041)
   at eval code (eval code:2:22)
   at Anonymous function (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:102499)
   at t (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:102041)
   at Anonymous function (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:102411)
   at Anonymous function (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:101935)
   at n (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:101591)
   at Anonymous function (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:269:101567)
   at t (https://nextjs-starter.now.sh/_next/8766e2d8101f161d4f7a9eec13b034f3/app.js:1:436)
```

Perhaps, some polyfill is required but I don't know how to identify it. Could you please fix it or at least help to understand which polyfill is required?

**Comment by lagivan** [comment]
It seems to be caused by `eval` of the code of `./src/client/next-auth-client.js`.

**Comment by iaincollins** [comment]
Thanks for filing this.

I've not seen this as recent versions have only been tested against Edge (and not Internet Explorer).

In previous releases https://polyfill.io has always taken care of compatibility for Internet Explorer. Maybe something about next-auth client is using webpack is doing something that doesn't work well in IE for some reason.

I'll leave this open, and create a ticket in next-auth to investigate and track this issue.

**Comment by zeldar** [comment]
@iaincollins Did this issue get resolved in next-auth?  Do you have a link to the issue?

**Comment by iaincollins** [comment]
Have raised an issue and referenced this one in it at https://github.com/iaincollins/next-auth/issues/31

There was an update with next-auth and webpack bundling in the last month or two which may or may not have resolved the issue, but I'm not able to test it right now to see if it's still happening (I don't have anything running any version of Internet Explorer as all systems and virtual machines I have are currently running Edge).

Will leave this open pending further feedback.

**Comment by iaincollins** [comment]
This issue should now be resolved and it's working in Internet Explorer 11 again.

All other dependancies have been upgraded in the latest update too.

There is some flicker in IE11 with dropdown menus on page load, but this is an HTML/CSS issue and will be resolved as separate update (probably by refactoring the dropdown menus).

Cause:

There was a problem with next-auth package, due to the bundle being generated by webpack not working in Internet Explorer 11 and causing it to bomb out.

The next-auth package now uses rollup to build the next-auth client; as there were other issues with recent release of webpack no longer generating viable isomorphic code.

Please re-open if you are still having problems.

**Comment by iaincollins** [comment]
Update: next-auth 1.11.0 (which was released today) now supports Internet Explorer 11.

* And possibly earlier versions, they have not been tested but sharing feedback here with others about what does/doesn't work is appreciated.
