### ISSUE TITLE
win .env

### ISSUE THREAD

**Issue by Naranbat1123** [iaincollins/nextjs-starter#80]
node v8.11.1 npm 5.6.0 npm run dev failed 
NODE_ENV=development PORT=3000 node index.js
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by iaincollins** [comment]
I think this is a duplicate of #75 (I assume is happening on Windows?) but please do comment if not.

(I think there is also another ticket about this somewhere…)
