### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by enterpriseSoftware** [iaincollins/nextjs-starter#81]
96168 error node v10.1.0
96169 error npm  v4.0.3
96170 error Cannot read property 'minimist' of undefined
96171 error If you need help, you may report this error at:
96171 error     <https://github.com/npm/npm/issues>
96172 verbose exit [ 1, true ]

**Comment by enterpriseSoftware** [comment]
npm update npm -g
fixed it

**Comment by iaincollins** [comment]
Thanks for the follow up.

For anyone reading this `node 8.11.1` (LTS) and `npm 6.0.0` are the current and supported versions.

\* _Node v7 through v10 should also be fine in practice but be sure NPM is up to date._
