### ISSUE TITLE
[Question] More database

### ISSUE THREAD

**Issue by tugal** [iaincollins/nextjs-starter#97]
Hi all,

Is other database supported ?
I'm not a big fan of mongodb, and i like to start side project with sqllite.

Is it a big effort ? i dont know very well your starter

Thanks,
Nelson

**Comment by tugal** [comment]
https://github.com/iaincollins/next-auth/issues/5

**Comment by iaincollins** [comment]
Happy to say with the [announcement of 2.0](#99) there will be out of the box support for a wide range of databases, including SQLite!
